version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "7071:7071"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    command: ["npm", "run", "start-docker"]